### ISSUE TITLE
Single Page Application

### ISSUE THREAD

**Issue by algonacci** [OpenProjects-id/Freeducation#1]
- [x] Halaman contact
- [x] Halaman about
- [x] Routing Library menggunakan Page.js
- [x] Halaman detail donasi
- [x] Halaman sukses donasi
- [x] Halaman gagal donasi
- [x] Halaman Not Found 404

**Comment by NurfitraPujo** [comment]
Mas ini buat desain UI-nya udah ada tah @algonacci

**Comment by algonacci** [comment]
> Mas ini buat desain UI-nya udah ada tah @algonacci

Tidak ada mas, hanya ada template html-nya saja, akan diconvert jadi Svelte. Untuk pengembangan mungkin nanti akan ada UI Design-nya atau lanjut pengembangan langsung implementasi

**Comment by algonacci** [comment]
Semua pages yang dilist sudah dibuat menjadi Single Page Application jadi tidak terlalu banyak merefresh halaman.
